### ISSUE TITLE
🐞 Scrollbar twitches around when scrolling large file

### ISSUE THREAD

**Issue by Eliulm** [CodeEditApp/CodeEditTextView#184]
### Description

When scrolling large files, the scrollbar twitches around the place. Only if the whole document has been completely viewed, the scrollbar will behave as expected.

Upon further investigation, I found that the `textview.frame.height` property changes a lot during scrolling. It might be the reason, why the scrollbar behaves weirdly.

### To Reproduce

1. Open file with content that does not fit in viewport.
2. Scroll

### Expected Behavior

Scrollbar animation should be smooth and `self.textView.frame.height` should stay constant during scrolling.

### Version Information

CodeEditTextView: 0.6.2
macOS: 13.3.1
Xcode: 14.3

### Screenshots

https://user-images.githubusercontent.com/82230675/235370078-81c50a53-5c0f-48c3-9ca0-aa4aeaa3b433.mov

**Comment by austincondiff** [comment]
Not sure if this is related or not, but when the scroll reaches line 100, things shift to the right to account for the additional digit. We should account for maximum ruler width upon file open, not on scroll. It seems like we do this for wrapped lines as well. My theory is that we assume all lines do not wrap. When we scroll to wrapped lines, this adds additional height to the overall scroll height and will adjust the scroll indicator to account for this additional height. (This is just a theory).

**Comment by Eliulm** [comment]
Interesting. However, I just tried this too, but I still get the twitching in a file without line wraps:

https://user-images.githubusercontent.com/82230675/235373888-cb418bd6-951b-4f8c-91d9-14b008e3cbe3.mov

**Comment by thecoolwinter** [comment]
There's two issues happening here:
- The issue brought up by @Eliulm is due to the text view not correctly estimating it's own height initially. There's some code that attempts to do this in `STTextView` [here](https://github.com/krzyzanowskim/STTextView/blob/a0135973aca7fb11a2de7164e85dc1f46a16297a/Sources/STTextView/STTextView.swift#L677) which updates as you scroll, apparently causing the last text element in the document to adjust it's `y` value as the document is scrolled.
- The ruler adjusting its width is due to the ruler view not counting lines until it comes across them, which was just a design decision by STTextView. Before it reaches the 100th line the ruler's width is determined by a 2-character width. Then when it loads the 3-character one it adjusts its width. This could be fixed with a pull request to STTextView, or it may be an opportunity to implement an in-house ruler view.

**Comment by austincondiff** [comment]
@thecoolwinter That makes a lot more sense. Well if it is any indication, when there is not enough text to fill the viewport, the view is vertically scrollable, the height is the viewport height plus the CodeEdit status bar height (which I want to say is a bottom edge inset. So maybe we are not taking edge insets into account?
